# Generated by Django 4.2.30 on 2026-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Customer inquiry, up to 2,000 characters.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Customer name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_or_email',
            field=models.CharField(help_text='A phone number or email address for your reply.', max_length=150),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='about_text',
            field=models.TextField(blank=True, help_text='Short story or introduction for the About page.'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='address',
            field=models.TextField(help_text='Full store address customers can use to visit.'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional store email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='map_embed_url',
            field=models.URLField(help_text='Google Maps embed URL, not a regular maps share link.'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='opening_hours',
            field=models.TextField(default='{}', help_text='Enter opening hours by day, for example: Monday-Friday: 10:00 AM-8:00 PM.'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='phone_number',
            field=models.CharField(help_text='Store phone number used by the Call buttons.', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='store_name',
            field=models.CharField(help_text='Name displayed across the website.', max_length=150),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='whatsapp_number',
            field=models.CharField(help_text='WhatsApp number with country code, digits only where possible.', max_length=20),
        ),
    ]
