# Generated by Django 4.2.30 on 2026-08-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_info', '0002_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': 'Shop information', 'verbose_name_plural': 'Shop information'},
        ),
    ]
