# Generated by Django 4.2.30 on 2026-08-31 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional introduction shown at the top of this category.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in menus.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional category image. Use JPEG, PNG, or WebP up to 10 MB.', null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this category from the website.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Customer-facing category name, such as Sofa or Bed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name; leave blank to generate it automatically.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Choose the furniture category for this item.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_variants',
            field=models.CharField(blank=True, help_text='Comma-separated options, such as Grey, Beige, Maroon.', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_info',
            field=models.CharField(blank=True, help_text='Delivery or installation terms for this item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Describe the item, its comfort, construction, and ideal use.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Format: 72in L x 34in W x 30in H.', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Flat amount to subtract from the regular price, in INR. Use 0 for no discount.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount (INR)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn off to hide this item without deleting it.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this item in the homepage featured section.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, help_text='Main materials, such as Sheesham wood or velvet.', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='The name customers will see in the catalog.', max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Regular selling price in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name; leave blank to generate it automatically.', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default='in_stock', help_text='Choose whether customers can currently inquire about this item.', max_length=20, verbose_name='availability'),
        ),
        migrations.AlterField(
            model_name='item',
            name='warranty_info',
            field=models.CharField(blank=True, help_text='Warranty coverage customers should know about.', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Short description for accessibility and search engines.', max_length=150),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the gallery.'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(help_text='Upload a JPEG, PNG, or WebP image up to 10 MB.', upload_to='items/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use this image as the item thumbnail and first gallery image.'),
        ),
    ]
