# Generated by Django 4.2.30 on 2026-08-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['display_order', 'id'], 'verbose_name_plural': 'Item images'},
        ),
    ]
