# Generated by Django 4.2.30 on 2026-08-31 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_itemimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount percentage to apply to the regular price. Use 0 for no discount.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount (%)'),
        ),
    ]
